version: '3'

services:
  postgresql_db:
    restart: always
    image: postgres
    container_name: "psql-container"
    environment:
      POSTGRES_USER: ${PG_SUPER_USER}
      POSTGRES_PASSWORD: ${PG_SUPER_PASSWORD}
    volumes:
      - psql_db:/var/lib/postgresql/data
    expose:
      - ${PG_PORT}
    env_file:
      - ../.env
    networks:
      - rest_api_restaurant
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: "api-container"
    environment:
      PG_HOST: "postgresql_db"
    volumes:
      - myapp:/usr/src/app
    expose:
      - '9000'
    depends_on:
      - postgresql_db
    networks:
      - rest_api_restaurant

  nginx:
    image: nginx:latest
    restart: always
    container_name: "nginx-container"
    depends_on:
      - api
      - postgresql_db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
      - '443:443'
    networks:
      - rest_api_restaurant

networks:
  rest_api_restaurant:
    driver: bridge

volumes:
  psql_db:
  myapp: