version: '3.9'

services:
  api:
    build:
      context: ..
      target: production
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: "restaurant-api"
    environment:
      PG_HOST: "postgresql_db"
    volumes:
      - restaurant-api:/usr/src/app
    expose:
      - '9000'
    depends_on:
      - ./docker-compose.base.yml./postgresql_db
    networks:
      - restaurant_network
    env_file:
      - ../.env

volumes:
  restaurant-db:
  restaurant-api: