version: '3.9'

services:
  postgresql_db:
    image: postgres
    restart: always
    container_name: "restaurant-db"
    environment:
      POSTGRES_USER: ${PG_SUPER_USER}
      POSTGRES_PASSWORD: ${PG_SUPER_PASSWORD}
    volumes:
      - restaurant-db:/var/lib/postgresql/data
    expose:
      - ${PG_PORT}
    env_file:
      - ../.env
    networks:
      - restaurant_network

  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    container_name: "restaurant-nginx"
    depends_on:
      - api
      - postgresql_db
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge

volumes:
  restaurant-db: